language: android
sudo: false
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-21
    - platform-tools
    - tools
  # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    